build: off
clone_depth: 30
clone_folder: c:\projects\ezpublish-kernel

skip_commits:
    message: /\[skip ci\]/i

init:
    - SET PATH=c:\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)
    - REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Command Processor" /v DelayedExpansion /t REG_DWORD /d 1 /f

install:
    - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
    - cd c:\php
    - IF %PHP%==1 appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-7.0.8-nts-Win32-VC14-x86.zip
    - IF %PHP%==1 7z x php-7.0.8-nts-Win32-VC14-x86.zip -y >nul
    - IF %PHP%==1 del /Q *.zip
    - IF %PHP%==1 copy /Y php.ini-development php.ini
    - IF %PHP%==1 echo max_execution_time=0 >> php.ini
    - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
    - IF %PHP%==1 echo extension=php_intl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_xsl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_gd2.dll >> php.ini
    - IF %PHP%==1 echo extension=php_pdo_sqlite.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
    - IF %PHP%==1 echo extension=php_curl.dll >> php.ini
    - IF %PHP%==1 echo memory_limit=512M >> php.ini
    - IF %PHP%==1 echo default_charset="utf-8" >> php.ini
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - IF %PHP%==1 appveyor DownloadFile https://getcomposer.org/download/1.1.3/composer.phar
    - cd c:\projects\ezpublish-kernel
    - composer update --no-progress --ansi

test_script:
    - cd c:\projects\ezpublish-kernel
    - copy /Y config.php-DEVELOPMENT config.php
    - SET X=0
    - vendor/bin/phpunit --colors=never -c phpunit.xml || SET X=!errorlevel!
    - vendor/bin/phpunit --colors=never -c phpunit-integration-legacy.xml || SET X=!errorlevel!
    - exit %X%
