parameters:
    ezpublish.search.solr.content.gateway.client.http.stream.class: eZ\Publish\Core\Search\Solr\Content\Gateway\HttpClient\Stream
    ezpublish.search.solr.content.criterion_visitor.aggregate.class: eZ\Publish\Core\Search\Solr\Content\CriterionVisitor\Aggregate
    ezpublish.search.solr.content.sort_clause_visitor.aggregate.class: eZ\Publish\Core\Search\Solr\Content\SortClauseVisitor\Aggregate
    ezpublish.search.solr.content.facet_builder_visitor.aggregate.class: eZ\Publish\Core\Search\Solr\Content\FacetBuilderVisitor\Aggregate
    ezpublish.search.solr.location.criterion_visitor.aggregate.class: eZ\Publish\Core\Search\Solr\Content\Location\CriterionVisitor\Aggregate
    ezpublish.search.solr.location.sort_clause_visitor.aggregate.class: eZ\Publish\Core\Search\Solr\Content\Location\SortClauseVisitor\Aggregate
    ezpublish.search.solr.location.facet_builder_visitor.aggregate.class: eZ\Publish\Core\Search\Solr\Content\Location\FacetBuilderVisitor\Aggregate
    ezpublish.search.solr.content.field_value_mapper.aggregate.class: eZ\Publish\Core\Search\Solr\Content\FieldValueMapper\Aggregate
    ezpublish.search.solr.content.field_name_generator.class: eZ\Publish\Core\Search\Solr\Content\FieldNameGenerator
    ezpublish.search.solr.field_registry.class: eZ\Publish\Core\Search\Solr\Content\FieldRegistry

services:
    ezpublish.search.solr.content.gateway.client.http.stream:
        class: %ezpublish.search.solr.content.gateway.client.http.stream.class%
        arguments:
            - %ezpublish.solr_server%

    # Note: services tagged with 'ezpublish.search.solr.content.criterion_visitor'
    # are registered to this one using compilation pass
    ezpublish.search.solr.content.criterion_visitor.aggregate:
        class: %ezpublish.search.solr.content.criterion_visitor.aggregate.class%

    # Note: services tagged with 'ezpublish.search.solr.content.sort_clause_visitor'
    # are registered to this one using compilation pass
    ezpublish.search.solr.content.sort_clause_visitor.aggregate:
        class: %ezpublish.search.solr.content.sort_clause_visitor.aggregate.class%

    # Note: services tagged with 'ezpublish.search.solr.content.facet_builder_visitor'
    # are registered to this one using compilation pass
    ezpublish.search.solr.content.facet_builder_visitor.aggregate:
        class: %ezpublish.search.solr.content.facet_builder_visitor.aggregate.class%

    # Note: services tagged with 'ezpublish.search.solr.content.field_value_mapper'
    # are registered to this one using compilation pass
    ezpublish.search.solr.content.field_value_mapper.aggregate:
        class: %ezpublish.search.solr.content.field_value_mapper.aggregate.class%

    # Note: services tagged with 'ezpublish.search.solr.location.criterion_visitor'
    # are registered to this one using compilation pass
    ezpublish.search.solr.location.criterion_visitor.aggregate:
        class: %ezpublish.search.solr.location.criterion_visitor.aggregate.class%

    # Note: services tagged with 'ezpublish.search.solr.location.sort_clause_visitor'
    # are registered to this one using compilation pass
    ezpublish.search.solr.location.sort_clause_visitor.aggregate:
        class: %ezpublish.search.solr.location.sort_clause_visitor.aggregate.class%

    # Note: services tagged with 'ezpublish.search.solr.location.facet_builder_visitor'
    # are registered to this one using compilation pass
    ezpublish.search.solr.location.facet_builder_visitor.aggregate:
        class: %ezpublish.search.solr.location.facet_builder_visitor.aggregate.class%

    ezpublish.search.solr.content.field_name_generator:
        class: %ezpublish.search.solr.content.field_name_generator.class%
