parameters:
    # Kernel related params
    webroot_dir: %kernel.root_dir%/../web

    ###
    # ezsettings namespace, default scope
    ###

    # Content/Location view
    ezsettings.default.location_view: {}
    ezsettings.default.content_view: {}
    ezsettings.default.block_view: {}

    # Common settings
    ezsettings.default.database.params: ~
    ezsettings.default.session_name: "eZSESSID{siteaccess_hash}"    # Using "{siteaccess_hash}" in session name makes it unique per siteaccess
    ezsettings.default.legacy_mode: false
    ezsettings.default.url_alias_router: true                       # Use UrlAliasRouter by default
    ezsettings.default.languages: []
    ezsettings.default.var_dir: "var"                   # The root directory where all log files, cache files and other stored files are created
    ezsettings.default.storage_dir: "storage"           # Where to place new files for storage, it's relative to var directory
    ezsettings.default.binary_dir: "original"

    # Content settings
    ezsettings.default.content.view_cache: true         # Whether to use content view cache or not (Etag/Last-Modified based)
    ezsettings.default.content.ttl_cache: false         # Whether to use TTL Cache for content (i.e. Max-Age response header)
    ezsettings.default.content.default_ttl: 60          # Default TTL cache value for content

    # Cache settings
    ezsettings.default.http_cache.purge_servers: ["http://localhost/"]   # Server(s) URL(s) that will be used for purging HTTP cache with PURGE requests.

    # Treemenu settings (admin interface)
    ezsettings.default.treemenu.http_cache: true        # Whether to use HttpCache or not for admin tree menu
    ezsettings.default.treemenu.ttl_cache: 86400        # If HttpCache is used, cache time to live in seconds

    # Templates to use while rendering fields
    ezsettings.default.field_templates:
        - {template: EzPublishCoreBundle::content_fields.html.twig, priority: 0}

    # Templates to use while rendering field definition settings
    ezsettings.default.fielddefinition_settings_templates:
        - {template: EzPublishCoreBundle::fielddefinition_settings.html.twig, priority: 0}


    # Image settings
    ezsettings.default.image.temporary_dir: imagetmp
    ezsettings.default.image.published_images_dir: images
    ezsettings.default.image.versioned_images_dir: images-versioned
    ezsettings.default.image_variations:
        reference:
            reference: ~
            filters:
                - {name: geometry/scaledownonly, params: [600, 600]}
        small:
            reference: reference
            filters:
                - {name: geometry/scaledownonly, params: [100, 100]}
        tiny:
            reference: reference
            filters:
                - {name: geometry/scaledownonly, params: [30, 30]}
        medium:
            reference: reference
            filters:
                - {name: geometry/scaledownonly, params: [200, 200]}
        large:
            reference: reference
            filters:
                - {name: geometry/scaledownonly, params: [300, 300]}
        rss:
            reference: reference
            filters:
                - {name: geometry/scale, params: [88, 31]}
        campaign:
            reference: ~
            filters:
                - {name: geometry/scalewidthdownonly, params: [770]}
                - {name: geometry/crop, params: [770, 390, 0, 0]}
        backgroundimage:
            reference: ~
            filters:
                - {name: geometry/scalewidthdownonly, params: [770]}
                - {name: geometry/crop, params: [770, 390, 0, 0]}
        highlighted:
            reference: ~
            filters:
                - {name: geometry/scalewidthdownonly, params: [300]}
                - {name: geometry/crop, params: [300, 300, 0, 0]}
        galleryfull:
            reference: ~
            filters:
                - {name: geometry/scalewidthdownonly, params: [770]}
        contentgrid:
            reference: ~
            filters:
                - {name: geometry/scalewidthdownonly, params: [770]}
                - {name: geometry/crop, params: [370, 160, 0, 0]}
        gallery:
            reference: ~
            filters:
                - {name: geometry/scalewidthdownonly, params: [770]}
                - {name: geometry/crop, params: [770, 390, 0, 0]}
        imagefull:
            reference: ~
            filters:
                - {name: geometry/scalewidthdownonly, params: [770]}

    # ImageMagick
    ezpublish.image.imagemagick.enabled: false
    ezpublish.image.imagemagick.executable_path:
    ezpublish.image.imagemagick.executable: convert
    ezsettings.default.imagemagick.pre_parameters:
    ezsettings.default.imagemagick.post_parameters:
    ezpublish.image.imagemagick.filters:
        geometry/scale: "-geometry {1}x{2}"
        geometry/scalewidth: "-geometry {1}"
        geometry/scaleheight: "-geometry x{1}"
        geometry/scaledownonly: "-geometry {1}x{2}>"
        geometry/scalewidthdownonly: "-geometry {1}>"
        geometry/scaleheightdownonly: "-geometry x{1}>"
        geometry/scaleexact: "-geometry {1}x{2}!"
        geometry/scalepercent: "-geometry {1}x{2}%"
        geometry/crop: "-crop {1}x{2}+{3}+{4}"
        filter/noise: "-noise {1}"
        filter/swirl: "-swirl {1}"
        colorspace/gray: "-colorspace GRAY"
        colorspace/transparent: "-colorspace Transparent"
        colorspace: "-colorspace {1}"
        border: "-border {1}x{2}"
        border/color: "-bordercolor rgb({1},{2},{3})"
        border/width: "-borderwidth {1}"
        flatten: "-flatten"
        resize: "-resize {1}"
        optimize: "-strip"

    ###
    # default ezpage settings
    ##
    ezpublish.ezpage.enabledLayouts: []
    ezpublish.ezpage.enabledBlocks: []
    ezpublish.ezpage.layouts:
        GlobalZoneLayout:
            name: Global zone layout
            template: globalzonelayout.tpl
        2ZonesLayout1:
            name: 2 zones (layout 1)
            template: 2zoneslayout1.tpl
        2ZonesLayout2:
            name: 2 zones (layout 2)
            template: 2zoneslayout2.tpl
        2ZonesLayout3:
            name: 2 zones (layout 3)
            template: 2zoneslayout3.tpl
        3ZonesLayout1:
            name: 3 zones (layout 1)
            template: 3zoneslayout1.tpl
        3ZonesLayout2:
            name: 3 zones (layout 2)
            template: 3zoneslayout2.tpl
        CallForActionLayout:
            name: Call For Action zone layout
            template: callforactionlayout.tpl

    ezpublish.ezpage.blocks:
        DemoBlock:
            name: Demo Block
        Manual2Items:
            name: 2 items (Manual)
        Manual3Items:
            name: 3 items (Manual)
        Manual4Items:
            name: 4 items (Manual)
        Manual5Items:
            name: 5 items (Manual)
        Dynamic3Items:
            name: 3 items (Dynamic)
        Gallery:
            name: Gallery (Manual)
        Video:
            name: Video (Manual)
        ItemList:
            name: Item list
        MainStory:
            name: Main story (Manual)
        Banner:
            name: Banner
        TagCloud:
            name: Tag cloud
        Poll:
            name: Poll
        FlashRecorder:
            name: Flash Recorder
        FeedReader:
            name: Feed reader
        Keyword:
            name: Keyword
        GMap:
            name: Google Map
        OnlineUsers:
            name: Online Users
        MultimediaCarousel:
            name: Multimedia carousel
        Search:
            name: Search
        Ads:
            name: Advertisement
        LatestContent:
            name: Latest content
        TopRated:
            name: Top Rated
        GMapItems:
            name: Google Map Items

    ###
    # Internal settings
    ###
    ezpublish.siteaccess.groups: {}
    ezpublish.siteaccess.groups_by_siteaccess: {}
