parameters:
    ezpublish.fieldType.class: eZ\Publish\Core\FieldType\FieldType
    ezpublish.fieldType.ezauthor.class: eZ\Publish\Core\FieldType\Author\Type
    ezpublish.fieldType.ezbinaryfile.class: eZ\Publish\Core\FieldType\BinaryFile\Type
    ezpublish.fieldType.ezbinaryfile.externalStorage.class: eZ\Publish\Core\FieldType\BinaryFile\BinaryFileStorage
    ezpublish.fieldType.ezbinaryfile.fileService.class: eZ\Publish\Core\MVC\Symfony\ConfiguredLocalFileService
    ezpublish.fieldType.ezbinaryfile.mimeTypeDetector.class: eZ\Publish\Core\FieldType\BinaryBase\MimeTypeDetector\FileInfoDetector
    ezpublish.fieldType.ezbinaryfile.pathGenerator.class: eZ\Publish\Core\FieldType\BinaryBase\PathGenerator\LegacyPathGenerator
    ezpublish.fieldType.ezboolean.class: eZ\Publish\Core\FieldType\Checkbox\Type
    ezpublish.fieldType.ezdatetime.class: eZ\Publish\Core\FieldType\DateAndTime\Type
    ezpublish.fieldType.ezemail.class: eZ\Publish\Core\FieldType\EmailAddress\Type
    ezpublish.fieldType.ezfloat.class: eZ\Publish\Core\FieldType\Float\Type
    ezpublish.fieldType.ezinteger.class: eZ\Publish\Core\FieldType\Integer\Type
    #ezpublish.fieldType.ezimage.class: eZ\Publish\Core\FieldType\Image\Type
    ezpublish.fieldType.ezkeyword.class: eZ\Publish\Core\FieldType\Keyword\Type
    ezpublish.fieldType.ezkeyword.externalStorage.class: eZ\Publish\Core\FieldType\Keyword\KeywordStorage
    ezpublish.fieldType.ezmedia.class: eZ\Publish\Core\FieldType\Media\Type
    ezpublish.fieldType.ezmedia.externalStorage.class: eZ\Publish\Core\FieldType\Media\MediaStorage
    ezpublish.fieldType.ezsrrating.class: eZ\Publish\Core\FieldType\Rating\Type
    ezpublish.fieldType.ezselection.class: eZ\Publish\Core\FieldType\Selection\Type
    ezpublish.fieldType.eztext.class: eZ\Publish\Core\FieldType\TextBlock\Type
    ezpublish.fieldType.ezstring.class: eZ\Publish\Core\FieldType\TextLine\Type
    ezpublish.fieldType.ezurl.class: eZ\Publish\Core\FieldType\Url\Type
    ezpublish.fieldType.ezurl.externalStorage.class: eZ\Publish\Core\FieldType\Url\UrlStorage
    ezpublish.fieldType.ezxmltext.class: eZ\Publish\Core\FieldType\XmlText\Type
    ezpublish.fieldType.ezxmltext.simplifiedInputParser.class: eZ\Publish\Core\FieldType\XmlText\Input\Parser\Simplified
    ezpublish.fieldType.ezxmltext.xmlSchema.class: eZ\Publish\Core\FieldType\XmlText\Schema
    ezpublish.fieldType.ezxmltext.xmlSchema.options: []
    # ezpublish.fieldType.ezxmltext.xmlSchema.options:
    #    customAttributes:
    #         table:
    #             - cellpadding
    #     classesList:
    #         paragraph:
    #             - pink
    #     customTags:
    #         underline:
    #             isInline: true
    ezpublish.fieldType.ezcountry.class: eZ\Publish\Core\FieldType\Country\Type
    ezpublish.fieldType.ezpage.class: eZ\Publish\Core\FieldType\Page\Type
    ezpublish.fieldType.ezpage.pageService.class: eZ\Publish\Core\FieldType\Page\Service
    ezpublish.fieldtype.ezpage.zoneDefinition: {}
    ezpublish.fieldType.ezpage.blockDefinition: {}
    # Temporary workaround to treat those field types as a ezstring until proper implementation will be in place
    ezpublish.fieldType.ezimage.class: eZ\Publish\Core\FieldType\TextLine\Type
    ezpublish.fieldType.ezgmaplocation.class: eZ\Publish\Core\FieldType\MapLocation\Type
    ezpublish.fieldType.ezgmaplocation.externalStorage.class: eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage
    ezpublish.fieldType.ezcomcomments.class: eZ\Publish\Core\FieldType\TextLine\Type
    ezpublish.fieldType.ezobjectrelationlist.class: eZ\Publish\Core\FieldType\TextLine\Type
    ezpublish.fieldType.ezuser.class: eZ\Publish\Core\FieldType\User\Type
    ezpublish.fieldType.ezuser.externalStorage.class: eZ\Publish\Core\FieldType\User\UserStorage

services:
    ezpublish.fieldType:
        class: %ezpublish.fieldType.class%
        abstract: true

    ezpublish.fieldType.ezauthor:
        class: %ezpublish.fieldType.ezauthor.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezauthor}

    ezpublish.fieldType.ezbinaryfile:
        class: %ezpublish.fieldType.ezbinaryfile.class%
        parent: ezpublish.fieldType
        arguments: [@ezpublish.fieldType.ezbinaryfile.fileService, @ezpublish.fieldType.ezbinaryfile.mimeTypeDetector]
        tags:
            - {name: ezpublish.fieldType, alias: ezbinaryfile}

    ezpublish.fieldType.ezbinaryfile.fileService:
        class: %ezpublish.fieldType.ezbinaryfile.fileService.class%
        arguments: [@ezpublish.config.resolver, %webroot_dir%, %binaryfile_identifier_prefix%]

    ezpublish.fieldType.ezbinaryfile.mimeTypeDetector:
        class: %ezpublish.fieldType.ezbinaryfile.mimeTypeDetector.class%

    ezpublish.fieldType.ezbinaryfile.pathGenerator:
        class: %ezpublish.fieldType.ezbinaryfile.pathGenerator.class%

    ezpublish.fieldType.ezbinaryfile.externalStorage:
        class: %ezpublish.fieldType.ezbinaryfile.externalStorage.class%
        arguments: [[], @ezpublish.fieldType.ezbinaryfile.fileService, @ezpublish.fieldType.ezbinaryfile.pathGenerator]
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: ezbinaryfile}

    ezpublish.fieldType.ezboolean:
        class: %ezpublish.fieldType.ezboolean.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezboolean}

    ezpublish.fieldType.ezdatetime:
        class: %ezpublish.fieldType.ezdatetime.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezdatetime}

    ezpublish.fieldType.ezemail:
        class: %ezpublish.fieldType.ezemail.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezemail}

    ezpublish.fieldType.ezfloat:
        class: %ezpublish.fieldType.ezfloat.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezfloat}

    ezpublish.fieldType.ezinteger:
        class: %ezpublish.fieldType.ezinteger.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezinteger}

    #ezpublish.fieldType.ezimage:
    #    class: %ezpublish.fieldType.ezimage.class%
    #    parent: ezpublish.fieldType
    #    tags:
    #        - {name: ezpublish.fieldType, alias: ezimage}

    ezpublish.fieldType.ezkeyword:
        class: %ezpublish.fieldType.ezkeyword.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezkeyword}

    ezpublish.fieldType.ezkeyword.externalStorage:
        class: %ezpublish.fieldType.ezkeyword.externalStorage.class%
        arguments: [[]]
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: ezkeyword}

    ezpublish.fieldType.ezmedia:
        class: %ezpublish.fieldType.ezmedia.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezmedia}

    ezpublish.fieldType.ezmedia.externalStorage:
        class: %ezpublish.fieldType.ezmedia.externalStorage.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: ezmedia}

    ezpublish.fieldType.ezsrrating:
        class: %ezpublish.fieldType.ezsrrating.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezsrrating}

    ezpublish.fieldType.ezselection:
        class: %ezpublish.fieldType.ezselection.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezselection}

    ezpublish.fieldType.eztext:
        class: %ezpublish.fieldType.eztext.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: eztext}

    ezpublish.fieldType.ezstring:
        class: %ezpublish.fieldType.ezstring.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezstring}

    ezpublish.fieldType.ezurl:
        class: %ezpublish.fieldType.ezurl.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezurl}

    ezpublish.fieldType.ezurl.externalStorage:
        class: %ezpublish.fieldType.ezurl.externalStorage.class%
        arguments: [[]]
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: ezurl}

    ezpublish.fieldType.ezxmltext:
        class: %ezpublish.fieldType.ezxmltext.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezxmltext}

    ezpublish.fieldType.ezxmltext.simplifiedInputParser:
        class: %ezpublish.fieldType.ezxmltext.simplifiedInputParser.class%
        public: false
        arguments:
            - @ezpublish.fieldType.ezxmltext.xmlSchema
        #   - {TrimSpaces: true, AllowMultipleSpaces: true}

    ezpublish.fieldType.ezxmltext.xmlSchema:
        class: %ezpublish.fieldType.ezxmltext.xmlSchema.class%
        arguments:
            - %ezpublish.fieldType.ezxmltext.xmlSchema.options%
        public: false

    ezpublish.fieldType.ezpage:
        class: %ezpublish.fieldType.ezpage.class%
        parent: ezpublish.fieldType
        arguments: [@ezpublish.fieldType.ezpage.pageService]
        tags:
            - {name: ezpublish.fieldType, alias: ezpage}

    ezpublish.fieldType.ezpage.pageService:
        class: %ezpublish.fieldType.ezpage.pageService.class%
        arguments: [%ezpublish.fieldtype.ezpage.zoneDefinition%, %ezpublish.fieldtype.ezpage.blockDefinition%]

    # Temporary workaround for ezemail, ezimage, ezgmaplocation, ezcomcomments, ezobjectrelationlist to treat those field types as
    # a ezstring until proper implementation will be in place

    ezpublish.fieldType.ezemail:
        class: %ezpublish.fieldType.ezemail.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezemail}

    ezpublish.fieldType.ezimage:
        class: %ezpublish.fieldType.ezimage.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezimage}

    ezpublish.fieldType.ezgmaplocation:
        class: %ezpublish.fieldType.ezgmaplocation.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezgmaplocation}

    ezpublish.fieldType.ezgmaplocation.externalStorage:
        class: %ezpublish.fieldType.ezgmaplocation.externalStorage.class%
        arguments: [[]]
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: ezgmaplocation}

    ezpublish.fieldType.ezcomcomments:
        class: %ezpublish.fieldType.ezcomcomments.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezcomcomments}

    ezpublish.fieldType.ezobjectrelationlist:
        class: %ezpublish.fieldType.ezobjectrelationlist.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezobjectrelationlist}

    ezpublish.fieldType.ezuser:
        class: %ezpublish.fieldType.ezuser.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezuser}

    ezpublish.fieldType.ezuser.externalStorage:
        class: %ezpublish.fieldType.ezuser.externalStorage.class%
        arguments: [[]]
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: ezuser}
