parameters:
    # Helpers
    ezpublish.translation_helper.class: eZ\Publish\Core\Helper\TranslationHelper
    ezpublish.field_helper.class: eZ\Publish\Core\Helper\FieldHelper
    ezpublish.content_preview_helper.class: eZ\Publish\Core\Helper\ContentPreviewHelper
    ezpublish.config_scope_listener.class: eZ\Bundle\EzPublishCoreBundle\EventListener\ConfigScopeListener
    ezpublish.dynamic_settings_listener.class: eZ\Bundle\EzPublishCoreBundle\EventListener\DynamicSettingsListener
    ezpublish.content_preview.location_provider.class: eZ\Publish\Core\Helper\PreviewLocationProvider
    ezpublish.config_resolver.resettable_services: []
    ezpublish.config_resolver.updateable_services: []

services:
    # Helpers
    ezpublish.translation_helper:
        class: "%ezpublish.translation_helper.class%"
        arguments:
            - "@ezpublish.config.resolver"
            - "@ezpublish.api.service.content"
            - "%ezpublish.siteaccesses_by_language%"
            - "@?logger"

    ezpublish.field_helper:
        class: "%ezpublish.field_helper.class%"
        arguments: ["@ezpublish.translation_helper", "@ezpublish.api.service.content_type", "@ezpublish.api.service.field_type"]

    ezpublish.content_preview_helper:
        class: "%ezpublish.content_preview_helper.class%"
        arguments: ["@event_dispatcher", "@ezpublish.siteaccess_router"]
        calls:
            - [setSiteAccess, ["@ezpublish.siteaccess"]]

    ezpublish.config_scope_listener:
        class: "%ezpublish.config_scope_listener.class%"
        arguments:
            $configResolvers: !tagged ezpublish.config.resolver
            $viewManager: "@ezpublish.view_manager"
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.dynamic_settings_listener:
        class: "%ezpublish.dynamic_settings_listener.class%"
        arguments:
            - "%ezpublish.config_resolver.resettable_services%"
            - "%ezpublish.config_resolver.updateable_services%"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.content_preview.location_provider:
        class: "%ezpublish.content_preview.location_provider.class%"
        arguments:
            - "@ezpublish.api.service.location"
            - "@ezpublish.api.service.content"
            - "@ezpublish.spi.persistence.cache.locationHandler"

    ezpublish.content_info_location_loader.main:
        class: 'eZ\Publish\Core\Helper\ContentInfoLocationLoader\SudoMainLocationLoader'
        arguments:
            - "@ezpublish.api.repository"

    eZ\Bundle\EzPublishCoreBundle\SiteAccess\LanguageResolver:
        parent: eZ\Publish\Core\Repository\SiteAccessAware\Language\AbstractLanguageResolver
        arguments:
            $configResolver: '@ezpublish.config.resolver'

    eZ\Publish\API\Repository\LanguageResolver:
        alias: eZ\Bundle\EzPublishCoreBundle\SiteAccess\LanguageResolver
