parameters:
    ezpublish.locale.conversion_map:
        alb-AL: sq_AL
        ara-SA: ar_SA
        bos-BA: bs_BA
        cat-ES: ca_ES
        chi-CN: zh_CN
        chi-HK: zh_HK
        chi-TW: zh_TW
        cro-HR: hr_HR
        cze-CZ: cs_CZ
        dan-DK: da_DK
        dut-NL: nl_NL
        ell-GR: el_GR
        eng-AU: en_AU
        eng-CA: en_CA
        eng-GB: en_GB
        eng-NZ: en_NZ
        eng-US: en_US
        epo-EO: eo
        esl-ES: es_ES
        esl-MX: es_MX
        fin-FI: fi_FI
        fre-BE: fr_BE
        fre-CA: fr_CA
        fre-CH: fr_CH
        fre-FR: fr_FR
        ger-CH: de_CH
        ger-DE: de_DE
        heb-IL: he_IL
        hin-IN: hi_IN
        hun-HU: hu_HU
        ind-ID: id_ID
        ita-CH: it_CH
        ita-IT: it_IT
        jpn-JP: ja_JP
        kor-KR: ko_KR
        mkd-MK: mk_MK
        nno-NO: nn_NO
        nor-NO: no_NO
        pol-PL: pl_PL
        por-BR: pt_BR
        por-MZ: pt_MZ
        por-PT: pt_PT
        rus-RU: ru_RU
        ser-SR: sr_RS
        slk-SK: sk_SK
        slo-SI: sl_SI
        sqi-AL: sq_AL
        srp-RS: sr_RS
        swe-SE: sv_SE
        tur-TR: tr_TR
        ukr-UA: uk_UA
        vie-VN: vi_VN

    ezpublish.locale.browser_map:
        au: ['eng-AU']
        be: ['fre-BE']
        br: ['por-BR']
        ca: ['eng-CA']
        cn: ['chi-CN']
        cz: ['cze-CZ']
        de: ['ger-DE']
        dk: ['dan-DK']
        en: ['eng-GB', 'eng-US']
        en_us: ['eng-US']
        es: ['esl-ES']
        fi: ['fin-FI']
        fr: ['fre-FR']
        gb: ['eng-GB']
        gr: ['ell-GR']
        hk: ['chi-HK']
        hr: ['cro-HR']
        hu: ['hun-HU']
        id: ['ind-ID']
        il: ['heb-IL']
        in: ['hin-IN']
        it: ['ita-IT']
        jp: ['jpn-JP']
        kr: ['kor-KR']
        mx: ['esl-MX']
        mz: ['por-MZ']
        nl: ['dut-NL']
        no: ['nor-NO']
        nz: ['eng-NZ']
        pl: ['pol-PL']
        pt: ['por-PT']
        rs: ['srp-RS']
        ru: ['rus-RU']
        sa: ['ara-SA']
        se: ['swe-SE']
        sk: ['slk-SK']
        tr: ['tur-TR']
        tw: ['chi-TW']
        ua: ['ukr-UA']

    ezpublish.locale.converter.class: eZ\Publish\Core\MVC\Symfony\Locale\LocaleConverter

services:
    ezpublish.locale.converter:
        class: "%ezpublish.locale.converter.class%"
        arguments: ["%ezpublish.locale.conversion_map%", "@logger"]

    # Overriding the original locale listener to trigger the internal locale conversion correctly.
    locale_listener:
        class: eZ\Bundle\EzPublishCoreBundle\EventListener\LocaleListener
        arguments: ["@request_stack", "%kernel.default_locale%", "@?router"]
        tags:
            - { name: kernel.event_subscriber }

    eZ\Publish\Core\MVC\Symfony\Locale\UserLanguagePreferenceProvider:
        autowire: true
        arguments:
            $languageCodesMap: '%ezpublish.locale.browser_map%'
            $localeFallback: '%locale_fallback%'
