parameters:
    twig.loader.string.class: Twig_Loader_String
    twig.extension.intl.class: Twig_Extensions_Extension_Intl

    ezpublish.twig.extension.content.class: eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension

    ezpublish.view_manager.class: eZ\Publish\Core\MVC\Symfony\View\Manager
    ezpublish.content_view.matcher_factory.class: eZ\Bundle\EzPublishCoreBundle\Matcher\ContentMatcherFactory
    ezpublish.location_view.matcher_factory.class: eZ\Bundle\EzPublishCoreBundle\Matcher\LocationMatcherFactory
    ezpublish.block_view.matcher_factory.class: eZ\Bundle\EzPublishCoreBundle\Matcher\BlockMatcherFactory
    ezpublish.content_view_provider.configured.class: eZ\Publish\Core\MVC\Symfony\View\Provider\Content\Configured
    ezpublish.location_view_provider.configured.class: eZ\Publish\Core\MVC\Symfony\View\Provider\Location\Configured
    ezpublish.block_view_provider.configured.class: eZ\Publish\Core\MVC\Symfony\View\Provider\Block\Configured
    ezpublish.content_view.viewbase_layout: "EzPublishCoreBundle::viewbase_layout.html.twig"
    ezpublish.content_view.content_block_name: "content"

    ezpublish.templating.global_helper.core.class: eZ\Publish\Core\MVC\Symfony\Templating\GlobalHelper
    ezpublish.twig.extension.core.class: eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\CoreExtension

services:
    twig.loader.string:
        class: %twig.loader.string.class%
        tags:
            - {name: twig.loader}

    twig.extension.intl:
        class: %twig.extension.intl.class%
        tags:
            - {name: twig.extension}

    ezpublish.twig.extension.content:
        class: %ezpublish.twig.extension.content.class%
        arguments: [@service_container, @ezpublish.config.resolver, @ezpublish.content_helper]
        tags:
            - {name: twig.extension}

    ezpublish.view_manager:
        class: %ezpublish.view_manager.class%
        arguments: [@templating, @event_dispatcher, @ezpublish.api.repository, %ezpublish.content_view.viewbase_layout%, @?logger]

    ezpublish.content_view_provider.configured:
        class: %ezpublish.content_view_provider.configured.class%
        arguments: [@ezpublish.content_view.matcher_factory]
        tags:
            - {name: ezpublish.content_view_provider, priority: 10}

    ezpublish.content_view.matcher_factory:
        class: %ezpublish.content_view.matcher_factory.class%
        arguments: [@service_container]

    ezpublish.location_view_provider.configured:
        class: %ezpublish.location_view_provider.configured.class%
        arguments: [@ezpublish.location_view.matcher_factory]
        tags:
            - {name: ezpublish.location_view_provider, priority: 10}

    ezpublish.location_view.matcher_factory:
        class: %ezpublish.location_view.matcher_factory.class%
        arguments: [@service_container]

    ezpublish.block_view_provider.configured:
        class: %ezpublish.block_view_provider.configured.class%
        arguments: [@ezpublish.block_view.matcher_factory]
        tags:
            - {name: ezpublish.block_view_provider, priority: 10}

    ezpublish.block_view.matcher_factory:
        class: %ezpublish.block_view.matcher_factory.class%
        arguments: [@service_container]

    ezpublish.templating.global_helper.core:
        class: %ezpublish.templating.global_helper.core.class%
        arguments: [@service_container]

    ezpublish.templating.global_helper:
        alias: ezpublish.templating.global_helper.core

    ezpublish.twig.extension.core:
        class: %ezpublish.twig.extension.core.class%
        arguments: [@ezpublish.templating.global_helper]
        tags:
            - {name: twig.extension}
