services:
    ezpublish.core.io.command.migrate_files:
        class: eZ\Bundle\EzPublishIOBundle\Command\MigrateFilesCommand
        arguments:
            - "%ez_io.metadata_handlers%"
            - "%ez_io.binarydata_handlers%"
            - "@ezpublish.core.io.migration.file_lister_registry"
            - "@ezpublish.core.io.migration.file_migrator"
        tags:
            - { name: console.command }

    ezpublish.core.io.migration.file_lister_registry:
        class: eZ\Bundle\EzPublishIOBundle\Migration\FileListerRegistry\ConfigurableRegistry

    ezpublish.core.io.migration.migration_handler:
        class: eZ\Bundle\EzPublishIOBundle\Migration\MigrationHandler
        arguments:
            - "@ezpublish.core.io.metadata_handler.registry"
            - "@ezpublish.core.io.binarydata_handler.registry"
            - "@logger"

    ezpublish.core.io.migration.file_lister.binary_file_lister:
        class: eZ\Bundle\EzPublishIOBundle\Migration\FileLister\BinaryFileLister
        parent: ezpublish.core.io.migration.migration_handler
        arguments:
            - "@ezpublish.core.io.migration.file_lister.file_iterator.binary_file_iterator"
            - "%ezsettings.default.binary_dir%"
        tags:
            - { name: "ezpublish.core.io.migration.file_lister", identifier: "binary_file" }
        lazy: true

    ezpublish.core.io.migration.file_lister.media_file_lister:
        class: eZ\Bundle\EzPublishIOBundle\Migration\FileLister\BinaryFileLister
        parent: ezpublish.core.io.migration.migration_handler
        arguments:
            - "@ezpublish.core.io.migration.file_lister.file_iterator.media_file_iterator"
            - "%ezsettings.default.binary_dir%"
        tags:
            - { name: "ezpublish.core.io.migration.file_lister", identifier: "media_file" }
        lazy: true

    ezpublish.core.io.migration.file_lister.image_file_lister:
        class: eZ\Bundle\EzPublishIOBundle\Migration\FileLister\ImageFileLister
        parent: ezpublish.core.io.migration.migration_handler
        arguments:
            - "@ezpublish.image_alias.variation_purger.legacy_storage_image_file.image_file_list"
            - "@ezpublish.image_alias.variation_path_generator"
            - "@liip_imagine.filter.configuration"
            - "%ezsettings.default.image.published_images_dir%"
        tags:
            - { name: "ezpublish.core.io.migration.file_lister", identifier: "image_file" }
        lazy: true

    ezpublish.core.io.migration.file_lister.file_iterator.binary_file_iterator:
        class: eZ\Bundle\EzPublishIOBundle\Migration\FileLister\FileIterator\LegacyStorageFileIterator
        arguments:
            - "@ezpublish.core.io.migration.file_lister.file_row_reader.binary_file_row_reader"

    ezpublish.core.io.migration.file_lister.file_iterator.media_file_iterator:
        class: eZ\Bundle\EzPublishIOBundle\Migration\FileLister\FileIterator\LegacyStorageFileIterator
        arguments:
            - "@ezpublish.core.io.migration.file_lister.file_row_reader.media_file_row_reader"

    eZ\Bundle\EzPublishIOBundle\Migration\FileLister\FileRowReader\LegacyStorageFileRowReader:
        arguments:
            $connection: '@ezpublish.persistence.connection'

    ezpublish.core.io.migration.file_lister.file_row_reader.binary_file_row_reader:
        class: eZ\Bundle\EzPublishIOBundle\Migration\FileLister\FileRowReader\LegacyStorageBinaryFileRowReader
        parent: eZ\Bundle\EzPublishIOBundle\Migration\FileLister\FileRowReader\LegacyStorageFileRowReader

    ezpublish.core.io.migration.file_lister.file_row_reader.media_file_row_reader:
        class: eZ\Bundle\EzPublishIOBundle\Migration\FileLister\FileRowReader\LegacyStorageMediaFileRowReader
        parent: eZ\Bundle\EzPublishIOBundle\Migration\FileLister\FileRowReader\LegacyStorageFileRowReader

    ezpublish.core.io.migration.file_migrator:
        class: eZ\Bundle\EzPublishIOBundle\Migration\FileMigrator\FileMigrator
        parent: ezpublish.core.io.migration.migration_handler

    # Builds the binarydata and metadata handler based on the siteaccess config
    ezpublish.core.io.metadata_handler:
        class: eZ\Publish\Core\IO\IOBinarydataHandler\SiteAccessDependentMetadataHandler
        arguments:
            $configResolver: '@ezpublish.config.resolver'
            $dataHandlerRegistry: '@ezpublish.core.io.metadata_handler.registry'

    ezpublish.core.io.binarydata_handler:
        class: eZ\Publish\Core\IO\IOBinarydataHandler\SiteAccessDependentBinaryDataHandler
        arguments:
            $configResolver: '@ezpublish.config.resolver'
            $dataHandlerRegistry: '@ezpublish.core.io.binarydata_handler.registry'

    ezpublish.core.io.metadata_handler.registry:
        class: eZ\Bundle\EzPublishIOBundle\ApiLoader\HandlerRegistry

    ezpublish.core.io.binarydata_handler.registry:
        class: eZ\Bundle\EzPublishIOBundle\ApiLoader\HandlerRegistry

    # Inject the siteaccess config into a few io services
    ezpublish.core.io.flysystem.default_adapter:
        class: eZ\Publish\Core\IO\Adapter\LocalAdapter
        arguments:
            - '@eZ\Publish\Core\IO\IOConfigProvider'
            - '@ezpublish.config.resolver'

    ezpublish.core.io.prefix_url_decorator:
        class: eZ\Publish\Core\IO\UrlDecorator\AbsolutePrefix
        arguments:
            - '@eZ\Publish\Core\IO\IOConfigProvider'

    # Base service for flysystem metadata handler
    ezpublish.core.io.metadata_handler.flysystem:
        abstract: true
        class: eZ\Publish\Core\IO\IOMetadataHandler\Flysystem
        arguments:
            - ~

    # Default flysystem metadata handler
    ezpublish.core.io.metadata_handler.flysystem.default:
        class: eZ\Publish\Core\IO\IOMetadataHandler\Flysystem
        arguments:
            - "@ezpublish.core.io.flysystem.default_filesystem"

    # Base service for flysystem binarydata handler
    ezpublish.core.io.binarydata_handler.flysystem:
        abstract: true
        class: eZ\Publish\Core\IO\IOBinarydataHandler\Flysystem
        arguments:
            - ~
            - "@ezpublish.core.io.default_url_decorator"

    # Default flysystem binarydata handler
    ezpublish.core.io.binarydata_handler.flysystem.default:
        class: eZ\Publish\Core\IO\IOBinarydataHandler\Flysystem
        arguments:
            - "@ezpublish.core.io.flysystem.default_filesystem"
            - "@ezpublish.core.io.default_url_decorator"

    ezpublish.core.io.image_fieldtype.legacy_url_decorator:
        class: eZ\Publish\Core\IO\UrlDecorator\Prefix
        arguments:
            - '@eZ\Publish\Core\IO\IOConfigProvider'

    ezpublish.core.io.stream_file_listener:
        class: eZ\Bundle\EzPublishIOBundle\EventListener\StreamFileListener
        arguments:
            - '@ezpublish.fieldType.ezimage.io_service'
            - '@eZ\Publish\Core\IO\IOConfigProvider'
        tags:
            - { name: kernel.event_subscriber }
