parameters:
    # Below default parameters, to be defined in app/config/config.yml
    #ezpublish_legacy.enabled: false
    #ezpublish_legacy.root_dir: ~

    ezpublish_legacy.kernel.lazy_loader.class: eZ\Publish\Core\MVC\Legacy\Kernel\Loader
    ezpublish_legacy.kernel_handler.class: ezpKernelHandler
    ezpublish_legacy.kernel_handler.web.class: ezpKernelWeb
    ezpublish_legacy.kernel_handler.treemenu.class: ezpKernelTreeMenu

    ezpublish_legacy.controller.class: eZ\Bundle\EzPublishLegacyBundle\Controller\LegacyKernelController
    ezpublish_legacy.treemenu.controller.class: eZ\Bundle\EzPublishLegacyBundle\Controller\LegacyTreeMenuController
    ezpublish_legacy.treemenu.controller.options: {}

    ezpublish_legacy.router.class: eZ\Bundle\EzPublishLegacyBundle\Routing\FallbackRouter
    ezpublish_legacy.url_generator.class: eZ\Bundle\EzPublishLegacyBundle\Routing\UrlGenerator
    ezpublish_legacy.siteaccess_mapper.class: eZ\Bundle\EzPublishLegacyBundle\LegacyMapper\SiteAccess
    ezpublish_legacy.session_mapper.class: eZ\Bundle\EzPublishLegacyBundle\LegacyMapper\Session
    ezpublish_legacy.configuration_mapper.class: eZ\Bundle\EzPublishLegacyBundle\LegacyMapper\Configuration
    ezpublish_legacy.content_exception_handler.class: eZ\Publish\Core\MVC\Legacy\EventListener\APIContentExceptionListener
    ezpublish_legacy.config.resolver.class: eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver
    ezpublish_legacy.config.default_scope: site

services:
    ezpublish_legacy.kernel:
        alias: ezpublish_legacy.kernel.lazy

    ezpublish_legacy.kernel.lazy:
        class: Closure
        factory_service: ezpublish_legacy.kernel.lazy_loader
        factory_method: buildLegacyKernel
        arguments: [@ezpublish_legacy.kernel_handler]

    ezpublish_legacy.kernel.lazy_loader:
        class: %ezpublish_legacy.kernel.lazy_loader.class%
        arguments:
            - %ezpublish_legacy.root_dir%
            - %webroot_dir%
            - @?logger

    ezpublish_legacy.kernel_handler.web:
        class: %ezpublish_legacy.kernel_handler.class%
        factory_service: ezpublish_legacy.kernel.lazy_loader
        factory_method: buildLegacyKernelHandlerWeb
        arguments: [@service_container, %ezpublish_legacy.kernel_handler.web.class%]

    ezpublish_legacy.kernel_handler.treemenu:
        class: %ezpublish_legacy.kernel_handler.treemenu.class%
        factory_service: ezpublish_legacy.kernel.lazy_loader
        factory_method: buildLegacyKernelHandlerTreeMenu
        arguments: [@service_container]

    ezpublish_legacy.kernel_handler:
        alias: ezpublish_legacy.kernel_handler.web

    ezpublish_legacy.controller:
        class: %ezpublish_legacy.controller.class%
        arguments: [@ezpublish_legacy.kernel, @templating]

    ezpublish_legacy.treemenu.controller:
        class: %ezpublish_legacy.treemenu.controller.class%
        arguments:
            - @ezpublish_legacy.kernel_handler.treemenu
            - @ezpublish_legacy.kernel.lazy_loader
            - %ezpublish_legacy.treemenu.controller.options%
        parent: ezpublish.controller.base
        scope: request

    ezpublish_legacy.router:
        class: %ezpublish_legacy.router.class%
        arguments: [@service_container, @?request_context, @?logger]
        tags:
            - {name: router, priority: -255}

    ezpublish_legacy.url_generator:
        class: %ezpublish_legacy.url_generator.class%
        arguments: [@ezpublish_legacy.kernel]
        parent: ezpublish.url_generator.base

    ezpublish_legacy.siteaccess_mapper:
        class: %ezpublish_legacy.siteaccess_mapper.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.session_mapper:
        class: %ezpublish_legacy.session_mapper.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.configuration_mapper:
        class: %ezpublish_legacy.configuration_mapper.class%
        arguments: [@ezpublish.config.resolver]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.content_exception_handler:
        class: %ezpublish_legacy.content_exception_handler.class%
        arguments: [@ezpublish_legacy.content_view_provider, @ezpublish_legacy.location_view_provider, @?logger]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.config.resolver:
        class: %ezpublish_legacy.config.resolver.class%
        arguments: [@ezpublish_legacy.kernel, %ezpublish_legacy.config.default_scope%]
        tags:
            - { name: ezpublish.config.resolver, priority: -255 }
