parameters:
    ezpublish_legacy.signalslot.assign_section.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyAssignSectionSlot
    ezpublish_legacy.signalslot.copy_content.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyCopyContentSlot
    ezpublish_legacy.signalslot.create_location.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyCreateLocationSlot
    ezpublish_legacy.signalslot.delete_content.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDeleteContentSlot
    ezpublish_legacy.signalslot.delete_location.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDeleteLocationSlot
    ezpublish_legacy.signalslot.delete_version.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDeleteVersionSlot
    ezpublish_legacy.signalslot.hide_location.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyHideLocationSlot
    ezpublish_legacy.signalslot.move_subtree.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyMoveSubtreeSlot
    ezpublish_legacy.signalslot.publish_version.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyPublishVersionSlot
    ezpublish_legacy.signalslot.set_content_state.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacySetContentStateSlot
    ezpublish_legacy.signalslot.create_object_state.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyCreateObjectStateSlot
    ezpublish_legacy.signalslot.create_object_state_group.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyCreateObjectStateGroupSlot
    ezpublish_legacy.signalslot.delete_object_state.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDeleteObjectStateSlot
    ezpublish_legacy.signalslot.delete_object_state_group.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDeleteObjectStateGroupSlot
    ezpublish_legacy.signalslot.set_priority_of_object_state.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacySetPriorityOfObjectStateSlot
    ezpublish_legacy.signalslot.update_object_state.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUpdateObjectStateSlot
    ezpublish_legacy.signalslot.update_object_state_group.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUpdateObjectStateGroupSlot
    ezpublish_legacy.signalslot.swap_location.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacySwapLocationSlot
    ezpublish_legacy.signalslot.unhide_location.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUnhideLocationSlot
    ezpublish_legacy.signalslot.update_location.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUpdateLocationSlot
    ezpublish_legacy.signalslot.publish_content_type_draft.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyPublishContentTypeDraftSlot
    ezpublish_legacy.signalslot.create_language.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyCreateLanguageSlot
    ezpublish_legacy.signalslot.delete_language.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDeleteLanguageSlot
    ezpublish_legacy.signalslot.disable_language.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyDisableLanguageSlot
    ezpublish_legacy.signalslot.enable_language.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyEnableLanguageSlot
    ezpublish_legacy.signalslot.update_language_name.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUpdateLanguageNameSlot
    ezpublish_legacy.signalslot.update_user.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUpdateUserSlot
    ezpublish_legacy.signalslot.assign_user_to_user_group.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyAssignUserToUserGroupSlot
    ezpublish_legacy.signalslot.unassign_user_from_user_group.class: eZ\Publish\Core\MVC\Legacy\SignalSlot\LegacyUnassignUserFromUserGroupSlot

services:
    ezpublish_legacy.signalslot.base:
        class: eZ\Publish\Core\MVC\Legacy\SignalSlot\AbstractLegacySlot
        arguments:
            - @ezpublish_legacy.kernel
            - @ezpublish_legacy.persistence_cache_purger
            - @ezpublish_legacy.switchable_http_cache_purger

    ezpublish_legacy.signalslot.assign_section:
        class: %ezpublish_legacy.signalslot.assign_section.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: SectionService\AssignSectionSignal }

    ezpublish_legacy.signalslot.copy_content:
        class: %ezpublish_legacy.signalslot.copy_content.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\CopyContentSignal }

    ezpublish_legacy.signalslot.create_location:
        class: %ezpublish_legacy.signalslot.create_location.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\CreateLocationSignal }

    ezpublish_legacy.signalslot.delete_content:
        class: %ezpublish_legacy.signalslot.delete_content.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\DeleteContentSignal }

    ezpublish_legacy.signalslot.delete_location:
        class: %ezpublish_legacy.signalslot.delete_location.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\DeleteLocationSignal }

    ezpublish_legacy.signalslot.delete_version:
        class: %ezpublish_legacy.signalslot.delete_version.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\DeleteVersionSignal }

    ezpublish_legacy.signalslot.hide_location:
        class: %ezpublish_legacy.signalslot.hide_location.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\HideLocationSignal }

    ezpublish_legacy.signalslot.move_subtree:
        class: %ezpublish_legacy.signalslot.move_subtree.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\MoveSubtreeSignal }

    ezpublish_legacy.signalslot.publish_version:
        class: %ezpublish_legacy.signalslot.publish_version.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\PublishVersionSignal }

    ezpublish_legacy.signalslot.set_content_state:
        class: %ezpublish_legacy.signalslot.set_content_state.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\SetContentStateSignal }

    ezpublish_legacy.signalslot.create_object_state:
        class: %ezpublish_legacy.signalslot.create_object_state.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\CreateObjectStateSignal }

    ezpublish_legacy.signalslot.create_object_state_group:
        class: %ezpublish_legacy.signalslot.create_object_state_group.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\CreateObjectStateGroupSignal }

    ezpublish_legacy.signalslot.delete_object_state:
        class: %ezpublish_legacy.signalslot.delete_object_state.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\DeleteObjectStateSignal }

    ezpublish_legacy.signalslot.delete_object_state_group:
        class: %ezpublish_legacy.signalslot.delete_object_state_group.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\DeleteObjectStateGroupSignal }

    ezpublish_legacy.signalslot.set_priority_of_object_state:
        class: %ezpublish_legacy.signalslot.set_priority_of_object_state.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\SetPriorityOfObjectStateSignal }

    ezpublish_legacy.signalslot.update_object_state:
        class: %ezpublish_legacy.signalslot.update_object_state.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\UpdateObjectStateSignal }

    ezpublish_legacy.signalslot.update_object_state_group:
        class: %ezpublish_legacy.signalslot.update_object_state_group.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\UpdateObjectStateGroupSignal }

    ezpublish_legacy.signalslot.swap_location:
        class: %ezpublish_legacy.signalslot.swap_location.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\SwapLocationSignal }

    ezpublish_legacy.signalslot.unhide_location:
        class: %ezpublish_legacy.signalslot.unhide_location.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\UnhideLocationSignal }

    ezpublish_legacy.signalslot.update_location:
        class: %ezpublish_legacy.signalslot.update_location.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\UpdateLocationSignal }

    ezpublish_legacy.signalslot.publish_content_type_draft:
        class: %ezpublish_legacy.signalslot.publish_content_type_draft.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: ContentTypeService\PublishContentTypeDraftSignal }

    ezpublish_legacy.signalslot.create_language:
        class: %ezpublish_legacy.signalslot.create_language.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: LanguageService\CreateLanguageSignal }

    ezpublish_legacy.signalslot.delete_language:
        class: %ezpublish_legacy.signalslot.delete_language.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: LanguageService\DeleteLanguageSignal }

    ezpublish_legacy.signalslot.disable_language:
        class: %ezpublish_legacy.signalslot.disable_language.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: LanguageService\DisableLanguageSignal }

    ezpublish_legacy.signalslot.enable_language:
        class: %ezpublish_legacy.signalslot.enable_language.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: LanguageService\EnableLanguageSignal }

    ezpublish_legacy.signalslot.update_language_name:
        class: %ezpublish_legacy.signalslot.update_language_name.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: LanguageService\UpdateLanguageNameSignal }

    ezpublish_legacy.signalslot.update_user:
        class: %ezpublish_legacy.signalslot.update_user.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: UserService\UpdateUserSignal }

    ezpublish_legacy.signalslot.assign_user_to_user_group:
        class: %ezpublish_legacy.signalslot.assign_user_to_user_group.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: UserService\AssignUserToUserGroupSignal }

    ezpublish_legacy.signalslot.unassign_user_from_user_group:
        class: %ezpublish_legacy.signalslot.unassign_user_from_user_group.class%
        parent: ezpublish_legacy.signalslot.base
        tags:
            - { name: ezpublish.api.slot, signal: UserService\UnAssignUserFromUserGroupSignal }
