parameters:
    ezplatform.installer.db_based_installer.class: EzSystems\PlatformInstallerBundle\Installer\DbBasedInstaller
    ezplatform.installer.clean_installer.class: EzSystems\PlatformInstallerBundle\Installer\CleanInstaller
    ezplatform.installer.install_command.class: EzSystems\PlatformInstallerBundle\Command\InstallPlatformCommand

services:
    EzSystems\PlatformInstallerBundle\Event\Subscriber\BuildSchemaSubscriber:
        autoconfigure: true
        public: false
        arguments:
            - '@=service("kernel").locateResource("@EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml")'

    ezplatform.installer.db_based_installer:
        abstract: true
        class:  "%ezplatform.installer.db_based_installer.class%"
        arguments: ["@ezpublish.persistence.connection"]
        lazy: true

    ezplatform.installer.clean_installer:
        class: "%ezplatform.installer.clean_installer.class%"
        parent: ezplatform.installer.db_based_installer
        tags:
            - {name: ezplatform.installer, type: clean}

    ezplatform.installer.install_command:
        class: "%ezplatform.installer.install_command.class%"
        arguments:
            - "@database_connection"
            - []
            - '@ezpublish.cache_pool'
            - "%kernel.environment%"
        tags:
            - { name: console.command, command: ezplatform:install }
