parameters:
    ezplatform.installer.db_based_installer.class: EzSystems\PlatformInstallerBundle\Installer\DbBasedInstaller
    ezplatform.installer.clean_installer.class: EzSystems\PlatformInstallerBundle\Installer\CleanInstaller
    ezplatform.installer.democlean_installer.class: EzSystems\PlatformInstallerBundle\Installer\DemoCleanInstaller
    ezplatform.installer.demo_installer.class: EzSystems\PlatformInstallerBundle\Installer\DemoInstaller

services:
    ezplatform.installer.db_based_installer:
        abstract: true
        class:  %ezplatform.installer.db_based_installer.class%
        arguments: [@database_connection]

    ezplatform.installer.democlean_installer:
        class: %ezplatform.installer.democlean_installer.class%
        parent: ezplatform.installer.db_based_installer

    ezplatform.installer.clean_installer:
        class: %ezplatform.installer.clean_installer.class%
        parent: ezplatform.installer.db_based_installer

    ezplatform.installer.demo_installer:
        class: %ezplatform.installer.demo_installer.class%
        parent: ezplatform.installer.db_based_installer
