parameters:
    ezplatform.installer.db_based_installer.class: EzSystems\PlatformInstallerBundle\Installer\DbBasedInstaller
    ezplatform.installer.clean_installer.class: EzSystems\PlatformInstallerBundle\Installer\CleanInstaller
    ezplatform.installer.install_command.class: EzSystems\PlatformInstallerBundle\Command\InstallPlatformCommand

services:
    EzSystems\PlatformInstallerBundle\Event\Subscriber\BuildSchemaSubscriber:
        autoconfigure: true
        public: false
        arguments:
            - '@=service("kernel").locateResource("@EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml")'

    EzSystems\PlatformInstallerBundle\Installer\DbBasedInstaller:
        abstract: true
        arguments: ["@ezpublish.persistence.connection"]
        lazy: true

    ezplatform.installer.db_based_installer:
        alias: EzSystems\PlatformInstallerBundle\Installer\DbBasedInstaller

    EzSystems\PlatformInstallerBundle\Installer\CoreInstaller:
        autowire: true
        parent: EzSystems\PlatformInstallerBundle\Installer\DbBasedInstaller
        tags:
            - {name: ezplatform.installer, type: clean}

    ezplatform.installer.clean_installer:
        deprecated: '%service_id% is deprecated since eZ Platform v2.5 LTS. Enable DoctrineSchemaBundle and use CoreInstaller instead'
        class: "%ezplatform.installer.clean_installer.class%"
        parent: ezplatform.installer.db_based_installer
        tags:
            - {name: ezplatform.installer, type: clean}

    ezplatform.installer.install_command:
        class: "%ezplatform.installer.install_command.class%"
        arguments:
            - "@database_connection"
            - []
            - '@ezpublish.cache_pool'
            - "%kernel.environment%"
        tags:
            - { name: console.command, command: ezplatform:install }
